# -*- coding: utf-8 -*-
"""Untitled17.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VpOg-4D7dBeb7B11DX7WvuGrxlMNfXhj
"""

print('Площадь прямоугольника')
print('_______________________')
a=int(input('Введите значение стороны A: '))
b=int(input('Введите значение стороны B: '))
print("-----------------------")
print('Площадь фигуры - ',a*b)